---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - "5601:5601"
  page-server:
    image: "nginx:stable"
    ports:
      - "6002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../pages:/www/data
